#!/bin/sh

printf 'Update Bootstrap? [y/N] : '
read -r updateBootstrap

case "$updateBootstrap" in
'y' | 'Y')
echo '[-] Downloading Lastest Bootstrap Version...'
wget $(curl -s https://api.github.com/repos/twbs/bootstrap/releases/latest | grep 'browser_' | cut -d\" -f4)
echo '[-] Unziping Bootstrap...'
mkdir tmp
unzip bootstrap*.zip -d tmp
echo '[-] Moving Bootstrap Files...'
rm -rf fonts
cd tmp/bootstrap*
mv fonts ../..
mv css/bootstrap.min.css ../../assets/css
mv css/bootstrap.min.css.map ../../assets/css
mv js/bootstrap.min.js ../../assets/js
cd ../..
echo '[-] Cleanup...'
rm -rf bootstrap-*.zip
rm -rf tmp
;;
'n' | 'N')
echo 'Bootstrap files were not updated!'
;;
*)
echo 'Whoa there...'
esac
